services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cocina
      POSTGRES_PASSWORD: cocina
      POSTGRES_DB: cocina
    ports:
      - "5432:5432"
    volumes:
      - cocina-postgres-data:/var/lib/postgresql/data

volumes:
  cocina-postgres-data:
